<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CartProduct;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * @param array $inCartProducts
     * @return mixed
     */
    public function findUserInterestedIn($inCartProducts = []){
        $inCartProductsID = [''];

        /**
         * @var CartProduct $cp
         */
        foreach($inCartProducts as $cp){
            $inCartProductsID[] = $cp->getProduct()->getId();
        }

        $qb = $this->createQueryBuilder('p');
        $query = $qb
            ->where($qb->expr()->notIn('p.id', $inCartProductsID))
            ->setMaxResults(4)
            ->getQuery();

        return $query->execute();
    }
}
