AppBundle\Entity\Media:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        location:
            type: string
            length: 255

    manyToOne:
        product:
            targetEntity: AppBundle\Entity\Product
            inversedBy: medias
            joinColumn:
                nullable: false

    lifecycleCallbacks: {  }
