AppBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        price:
            type: integer

    oneToMany:
        medias:
            targetEntity: AppBundle\Entity\Media
            mappedBy: product

        cartProducts:
            targetEntity: AppBundle\Entity\CartProduct
            mappedBy: product

    lifecycleCallbacks: {  }
